using System;

namespace Euler.Problems
{
    public class Problem002 : ProblemBase
    {
        public Problem002()
            : base(
                title: "Even Fibonacci numbers",
                description: string.Join(Environment.NewLine + Environment.NewLine,
                    "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:",
                    "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...",
                    "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms."),
                answer: 4613732)
        {
        }

        public override long Solve()
        {
            const long limit = 4000000;

            long term1 = 1;
            long term2 = 2;

            long answer = 0;
            while (term2 <= limit)
            {
                if (term2 % 2 == 0)
                {
                    answer += term2;
                }

                long temp = term1 + term2;
                term1 = term2;
                term2 = temp;
            }
            return answer;
        }
    }
}